// Animal registry -- development harness. Serves the registry API over an
// IN-MEMORY fixture herd.
//
//   npm run registry:harness -w server
//   npm run registry:harness -w server -- --port=4100
//
// ---------------------------------------------------------------------------
// HARD CONSTRAINT: never import `../db`.
// ---------------------------------------------------------------------------
// The standing rule for this cycle is that nothing synthetic ever touches
// registry_animals in dairy.db. The registry holds the only records in this
// repo that cannot be regenerated by re-running a seed, and "I will delete them
// after" is exactly how they stop being the only records.
//
// `../db` opens dairy.db at module load, so an import alone breaks it --
// the same trap captureIsolation.test.ts exists for on the Cycle 7 capture
// tooling, and registry.harness.test.ts asserts the same absence here.
//
// This is what makes it possible to build the entry forms against real-shaped
// data -- the awkward-case herd from fixtures.ts, with a dry-off close, an
// inferred close, an open lactation, a stillbirth, a departed animal and a
// paired correction -- without a single synthetic row reaching the real file.
//
// Everything this serves is DISCARDED when the process exits. There is no
// persistence and there must never be one: a harness that saved its state
// would be a second registry, and the next question would be how to merge it.

import express from 'express';
import cors from 'cors';

import { registryRouter } from './routes';
import { freshDb, tradingHerd } from './fixtures';
import { farmToday } from './time';
import { herd } from './reads';
import type { Db } from './schema';

interface Args {
  port: number;
  empty: boolean;
  help: boolean;
}

export function parseArgs(argv: string[]): Args {
  const args: Args = { port: 4100, empty: false, help: false };
  for (const raw of argv) {
    const [flag, value] = raw.split('=');
    switch (flag) {
      case '--port':
        args.port = Number(value);
        if (!Number.isInteger(args.port) || args.port < 1) {
          throw new Error(`--port must be a positive integer, got '${value}'`);
        }
        break;
      case '--empty':
        args.empty = true;
        break;
      case '--help':
      case '-h':
        args.help = true;
        break;
      default:
        throw new Error(`unknown flag '${raw}'\n\n${USAGE}`);
    }
  }
  return args;
}

const USAGE = `
Usage:
  npm run registry:harness -w server [-- --port=4100] [-- --empty]

Serves /api/registry over an IN-MEMORY fixture herd. Never opens dairy.db.

  --port=<n>   default 4100 (the real server uses 4000)
  --empty      start with an empty registry instead of the fixture herd

  --empty is not a throwaway option: the empty and one-row states are what the
  first hour of real entry looks like, and they should be built rather than
  discovered. Use it to work on them deliberately.

Everything is discarded on exit. There is no persistence, and there must not be
one -- a harness that saved its state would be a second registry.
`.trim();

/** Build the harness app over a caller-supplied handle. Exported for tests. */
export function harnessApp(db: Db): express.Express {
  const app = express();
  app.use(cors());
  app.use(express.json({ limit: '2mb' }));
  app.use('/api/registry', registryRouter(db));

  // A banner endpoint, so a client can tell at a glance that it is talking to
  // the harness and not the real server. Worth the four lines: the forms write
  // real records, and "which database am I pointed at" should never be a guess.
  app.get('/api/harness', (_req, res) => {
    res.json({
      harness: true,
      storage: ':memory:',
      warning: 'fixture data, discarded on exit -- this is NOT dairy.db',
      animals: herd(db).length,
      destinations: (
        db.prepare(`SELECT COUNT(*) n FROM registry_destinations`).get() as { n: number }
      ).n,
    });
  });

  return app;
}

function main(): void {
  const args = parseArgs(process.argv.slice(2));
  if (args.help) {
    console.log(USAGE);
    return;
  }

  // tradingHerd() rather than cleanHerd(): the awkward-case herd PLUS two
  // weeks of milk yield and sales. The reconciliation screen has production on
  // one side and dispatch on the other, so a fixture with only the herd would
  // leave half of every sales screen rendering an empty state.
  //
  // ENDING TODAY, not at the frozen AS_OF. The harness reads the real clock, so
  // a fixture that stopped days ago opened every sales screen onto an empty
  // session -- correct, and indistinguishable from broken. The default stays
  // frozen for the tests; only this caller moves with the calendar.
  const db = args.empty ? freshDb() : tradingHerd(farmToday()).db;
  const app = harnessApp(db);

  app.listen(args.port, () => {
    const rows = herd(db);
    console.log(`registry harness  http://localhost:${args.port}/api/registry`);
    console.log(`  storage     :memory:  (dairy.db is NOT open in this process)`);
    console.log(`  herd        ${rows.length} animal(s)${args.empty ? '  [--empty]' : ''}`);
    for (const r of rows) {
      console.log(
        `    ${r.id}  ${(r.name ?? '-').padEnd(8)} ${String(r.status).padEnd(10)} ` +
          `parity ${r.parity}  ${r.event_count} event(s)`,
      );
    }
    console.log('\n  Everything here is discarded when this process exits.');
  });
}

if (require.main === module) main();
