// Module-isolation guard for the registry harness and its routes.
//
// The standing rule for this cycle: NOTHING SYNTHETIC EVER TOUCHES
// registry_animals in dairy.db. The registry holds the only records in this
// repo that cannot be regenerated by re-running a seed, and "I will delete them
// after" is precisely how they stop being the only records -- the previous two
// cycles each ended with a manual DROP of walkthrough data, which worked
// because someone remembered.
//
// The rule is enforced by an ABSENCE: harness.ts and routes.ts must not import
// `../db`, directly or transitively. An absence is exactly the kind of
// invariant that gets broken later by a one-line import that looks harmless --
// `import { db } from '../db'` is the most natural thing in the world to write
// in a route file, and it would silently point the harness at the real herd.
//
// Same shape, and the same reasoning, as captureIsolation.test.ts.

import assert from 'node:assert';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { test } from 'node:test';

/**
 * Modules whose presence in the require cache means the constraint broke.
 *
 * `better-sqlite3` is NOT forbidden here, unlike in captureIsolation: the
 * harness must open an `:memory:` database, so it legitimately loads the
 * driver. What it must never load is the module that opens the FILE.
 */
const FORBIDDEN = [/[/\\]src[/\\]db\.ts$/, /[/\\]src[/\\]seed\.ts$/];

function offendingModules(): string[] {
  return Object.keys(require.cache).filter((p) => FORBIDDEN.some((re) => re.test(p)));
}

test('the harness and the routes never load db.ts or seed.ts', () => {
  // Sanity: if something else in this process already pulled the database in,
  // the assertion below would be vacuous rather than failing.
  assert.deepEqual(
    offendingModules(),
    [],
    'a database module was already loaded before this test ran — the check would be meaningless',
  );

  // Load exactly what a harness run loads. Its CLI entry is behind
  // `require.main === module`, so this imports without starting a server.
  require('./harness');
  require('./routes');
  require('./reads');
  require('./fixtures');
  require('./entry');
  require('./calving');
  require('./projectStore');
  require('./store');
  require('./verify');

  assert.deepEqual(
    offendingModules(),
    [],
    'the registry harness now reaches dairy.db — the no-synthetic-rows rule is broken. ' +
      'Check for a new `import { db } from "../db"` in harness.ts, routes.ts, reads.ts, ' +
      'or anything they import. Routes take a `db` HANDLE; they must not fetch the singleton.',
  );
});

test('no harness-reachable module names the forbidden imports at all', () => {
  // The static half, for the same reason captureIsolation has one: a future
  // helper could reach the singleton through a path this test does not require.
  const read = (f: string): string => readFileSync(path.join(__dirname, f), 'utf8');

  for (const file of [
    'harness.ts',
    'routes.ts',
    'reads.ts',
    'fixtures.ts',
    'entry.ts',
    'calving.ts',
    'projectStore.ts',
    'store.ts',
    'project.ts',
    'invariants.ts',
    'verify.ts',
    'schema.ts',
    'events.ts',
    'errors.ts',
    'intervals.ts',
    'time.ts',
    'types.ts',
    'cli.ts',
  ]) {
    const src = read(file);
    for (const forbidden of ["'../db'", "'../seed'"]) {
      assert.ok(
        !new RegExp(`from ${forbidden.replace(/[./]/g, '\\$&')};`).test(src),
        `${file} imports ${forbidden} — the harness must never open dairy.db`,
      );
    }
  }
});

test('exactly the CLI entry points import ../db, and nothing else does', () => {
  // The other side of the same rule, stated positively: reaching the singleton
  // is a TRANSPORT decision, made in one place per command. If this list grows,
  // something that should take a handle stopped doing so.
  const dir = path.join(__dirname);
  const { readdirSync } = require('node:fs') as typeof import('node:fs');

  // BOTH forms, deliberately. This used to match `from '../db';` alone, which
  // meant a module could reach the singleton through `require('../db')` and not
  // register here at all -- and two files now do exactly that on purpose
  // (verifyRegistry.ts under --db, and backup.ts, whose static import would be a
  // require cycle since db.ts imports IT for the pre-migration hook). Matching
  // only the static form would have quietly turned this guard off for them.
  const reachesSingleton = /(from '\.\.\/db';|require\('\.\.\/db'\))/;
  const importers = readdirSync(dir)
    .filter((f) => f.endsWith('.ts') && !f.endsWith('.test.ts'))
    .filter((f) => reachesSingleton.test(readFileSync(path.join(dir, f), 'utf8')))
    .sort();

  assert.deepEqual(
    importers,
    [
      'add.ts',
      'backup.ts',
      'calve.ts',
      'correct.ts',
      'event.ts',
      'rebuild.ts',
      'verifyRegistry.ts',
    ],
    'only the seven CLI entry points may reach the db singleton',
  );
});

test('the harness serves :memory: and says so', () => {
  const src = readFileSync(path.join(__dirname, 'harness.ts'), 'utf8');
  assert.match(src, /':memory:'/, 'the banner names its storage');
  assert.match(src, /NOT dairy\.db/, 'and warns plainly');
  // No persistence path: the harness must not construct a database of its own
  // (it takes one from fixtures.ts, which is always `:memory:`) and must not
  // write files. A harness that saved its state would be a second registry, and
  // the next question would be how to merge it.
  //
  // Asserted on the CODE, not on prose -- a first attempt at this matched the
  // word "persistence" in this file's own comments and failed for that reason.
  const code = src
    .split('\n')
    .filter((l) => !l.trimStart().startsWith('//') && !l.trimStart().startsWith('*'))
    .join('\n');
  assert.ok(!/new Database\(/.test(code), 'the harness opens no database of its own');
  assert.ok(!/writeFile|appendFile|createWriteStream/.test(code), 'the harness writes no files');
});
